\import Function

\func \infixr 8 o {A B C : \Type} (g : B -> C) (f : A -> B) => \lam x => g (f x)

\func id {A : \Type} => \lam (x : A) => x


\class Functor
  (F : \Type  -> \Type) {
  | map {A B : \Type} (A -> B) : (F A) -> F B
  | map-id {A : \Type} (y : F A) : map id y = y
  | map-comp {A B C : \Type} (f : A -> B) (g : B -> C) (y : F A) : map (g o f) y = map g (map f y)

  \func <$ {A B : \Type} (a : A) (fb : F B) : F A =>
    map (\lam _ => a) fb
}