\import core.data.Maybe (pure)
\import core.typeclasses.Applicative

\class Monad \extends Applicative {
  | pure {A : \Type } A : F A
  | flatMap {A B : \Type} (f : A -> F B) (fa : F A) : F B
  -- laws
  | right-unit {A B : \Type} (f : A -> F B) (a : A) : flatMap f (pure a) = f a
  | left-unit {A B : \Type} (f : A -> F B) (a : F A) : flatMap pure a = a
  | m-assoc {A B C : \Type} (f : A -> F B) (g : B -> F C) (a : F A) : flatMap g (flatMap f a) = flatMap (\lam a => flatMap g (f a)) a
}